# netlify.toml

[build]
  # No build command needed for static HTML site
  publish = "."  # Publish the root directory

[build.environment]
  NODE_VERSION = "18"  # Specify Node.js version if needed by build or functions

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content-Security-Policy: Allows self, Google Fonts, data URIs, Netlify API.
    # Enforces external scripts and styles (no 'unsafe-inline').
    # This is more secure but requires all JS/CSS to be in external files
    # or <style> blocks in <head>. Inline styles/scripts will be blockedo.


    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://api.netlify.com;"

# [[redirects]] section removed - Netlify handles 404s automatically
# if a 404.html file exists in the publish directory.
# Ensure you have a 404.html file in your root directory ('.').
