[build]
  command = "npm run build"
  publish = ".next"  # For Next.js 12+ (or "out" if you customized the output)
  functions = "functions"  # If using Netlify Functions

[build.environment]
  NODE_VERSION = "18"  # Must match your package.json "engines"
  NEXT_TELEMETRY_DISABLED = "1"  # Disables Next.js telemetry

# Next.js requires these headers for proper functioning
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://api.netlify.com;"

# Required for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Language = ["en"], Country = ["US"]}

# For 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true

[dev]
  framework = "nextjs"
  targetPort = 3000
  autoLaunch = true