# Netlify configuration file

# Build settings
[build]
  publish = "/"
  command = "echo 'Static site, no build step required'"

# Headers to set on all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://api.netlify.com;"

# Redirect all 404s to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling
[build.processing.forms]
  # Enable Netlify forms
  enabled = true
